-- ============================================================
-- SIMPELBIZ
-- DATABASE SETUP SUPABASE
-- ============================================================

-- ============================================================
-- 1. TABLE BERKAS
-- ============================================================

create table if not exists public.berkas (
    id bigint generated by default as identity primary key,

    nama_badan_hukum text not null,
    kategori text not null,

    nama_client text,
    jenis_layanan text,

    status text not null default 'Proses',

    metode_pengambilan text default 'Belum Dipilih',

    pengiriman text default 'Belum Dikirim',

    stempel text default 'Belum',

    tanggal_masuk date default current_date,

    catatan text,

    created_at timestamptz default now(),

    updated_at timestamptz default now()
);


-- ============================================================
-- 2. ENABLE ROW LEVEL SECURITY
-- ============================================================

alter table public.berkas enable row level security;


-- ============================================================
-- 3. HAPUS POLICY LAMA
-- ============================================================

drop policy if exists "berkas_select_authenticated"
on public.berkas;

drop policy if exists "berkas_insert_authenticated"
on public.berkas;

drop policy if exists "berkas_update_authenticated"
on public.berkas;

drop policy if exists "berkas_delete_authenticated"
on public.berkas;


-- ============================================================
-- 4. POLICY SELECT
-- ============================================================

create policy "berkas_select_authenticated"
on public.berkas
for select
to authenticated
using (true);


-- ============================================================
-- 5. POLICY INSERT
-- ============================================================

create policy "berkas_insert_authenticated"
on public.berkas
for insert
to authenticated
with check (true);


-- ============================================================
-- 6. POLICY UPDATE
-- ============================================================

create policy "berkas_update_authenticated"
on public.berkas
for update
to authenticated
using (true)
with check (true);


-- ============================================================
-- 7. POLICY DELETE
-- ============================================================

create policy "berkas_delete_authenticated"
on public.berkas
for delete
to authenticated
using (true);


-- ============================================================
-- 8. DATA CONTOH
-- ============================================================

insert into public.berkas
(
    nama_badan_hukum,
    kategori,
    nama_client,
    jenis_layanan,
    status,
    metode_pengambilan,
    pengiriman,
    stempel,
    tanggal_masuk,
    catatan
)
values

(
    'PT Maju Bersama',
    'Pendirian',
    'Budi Santoso',
    'Pendirian PT',
    'Selesai',
    'Diambil Client',
    'Belum Dikirim',
    'Sudah',
    current_date,
    'Berkas telah selesai'
),

(
    'CV Sinar Jaya',
    'Perubahan',
    'Andi Wijaya',
    'Perubahan CV',
    'Proses',
    'JNE',
    'Belum Dikirim',
    'Belum',
    current_date,
    'Menunggu proses'
);


-- ============================================================
-- 9. INDEX
-- ============================================================

create index if not exists idx_berkas_status
on public.berkas(status);

create index if not exists idx_berkas_kategori
on public.berkas(kategori);

create index if not exists idx_berkas_tanggal
on public.berkas(tanggal_masuk);